export { RoolClient, roolSdkVersion } from "./client.js";
export { EmailChangeError, RoolAuthUnavailableError } from "./auth-base.js";
export type { EmailChangeErrorCode } from "./auth-base.js";
export { BrowserAuth } from "./auth-browser.js";
export type { BrowserAuthConfig } from "./auth-browser.js";
export { NativeAuth } from "./auth-native.js";
export type { NativeAuthConfig, NativeAuthProvider } from "./auth-native.js";
export { RoolProblem } from "./problem.js";
export { RoolFileError } from "./files.js";
export type {
  AgentRequestOptions,
  MachineAgent,
  MachineAgentCreateInput,
  MachineAgentDefinition,
  MachineAgents,
  MachineAssistantFinish,
  MachineConversation,
  MachineConversationCancelOptions,
  MachineConversationContentPart,
  MachineConversationCreateOptions,
  MachineConversationFollowOptions,
  MachineConversationMetadata,
  MachineConversationListener,
  MachineConversationMetadataInput,
  MachineConversationPromptOptions,
  MachineConversationState,
  MachineConversationSummary,
  MachineConversationTurn,
  MachineConversationTurnRole,
  MachineConversationView,
  MachineConversationVisibility,
  MachinePromptEffort,
  MachineRunEvent,
} from "./agents.js";
export { isRoolObjectPath } from "./structured.js";
export type {
  RoolAccountEvent,
  RoolClientEvent,
  RoolEvents,
} from "./events.js";
export type {
  MachineDirectoryCreateOptions,
  MachineFileAccess,
  MachineFileAccessAudience,
  MachineFileCapabilities,
  MachineFileCopyOptions,
  MachineFileDeleteMultipleOptions,
  MachineFileDeleteOptions,
  MachineFileDeleteResult,
  MachineFileDeleteTarget,
  MachineFileInfo,
  MachineFileListOptions,
  MachineFilePath,
  MachineFiles,
  MachineFileRange,
  MachineFileReadMultipleOptions,
  MachineFileReadOptions,
  MachineFileReadResult,
  MachineFileTransferOptions,
  MachineFileTransferResult,
  MachineFileTree,
  MachineFileTreeChange,
  MachineFileTreeListOptions,
  MachineFileUploadProgress,
  MachineFileWriteBody,
  MachineFileWriteOptions,
  MachineStorageUsage,
} from "./files.js";
export type {
  MachineCheckpointsApi,
  MachineInvitesApi,
  MachineMembersApi,
  MachineSettingsApi,
  RoolMachine,
} from "./machine.js";
export type {
  CollectionDef,
  FieldDef,
  FieldType,
  MachineCollection,
  MachineCollectionPath,
  MachineCollectionsApi,
  MachineMetadata,
  MachineMetadataApi,
  MachineObjectsApi,
  MachineStructuredRequestOptions,
  RoolObject,
  RoolObjectMoveOptions,
  RoolObjectPath,
  RoolObjectRemoveResult,
  SpaceSchema,
} from "./structured.js";
export type {
  ClientCompatibility,
  CreateMachineInvite,
  CreatedMachineInvite,
  Voucher,
  VoucherClaimResult,
  VoucherList,
  VoucherPayload,
  VoucherPreview,
  VoucherUpdate,
  Greeting,
  InviteRedemption,
  InviteRedemptionStatus,
  MachineCheckpoint,
  MachineCheckpointCollection,
  MachineFetchInit,
  MachineInvite,
  MachineInviteEmailStatus,
  MachineInvitePreview,
  MachineInviteRole,
  MachineLifecycleState,
  MachineMember,
  MachineMemberRoleConfiguration,
  MachineMeta,
  MachineRole,
  MachineSettings,
  MachineSummary,
  PasswordSignInResult,
  RoolAuth,
  RoolClientConfig,
  RoolClientIdentity,
  RoolPlan,
  RoolProblemDetails,
  RoolRequestTokens,
  RoolSession,
  RoolTokenSource,
  ServerInfo,
  SpeechmaticsToken,
  SpeechmaticsTokenOptions,
  OptionalProvider,
  ProviderDisclosure,
  Providers,
  UserAccount,
  UserAppData,
  UserProfile,
} from "./types.js";
